apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-1
  labels: 
    app: demo
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: maripavlova/myhello